config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cabinets
  root to: 'pages#home'
  get 'pages/pro'
  get 'pages/public'
  get 'pages/paris'
  get 'pages/mentionslegales'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cabinet.rb
class Cabinet < ApplicationRecord
  geocoded_by :address
  has_many_attached :photos
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :nom,      :validate => true
  attribute :email,      :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :telephone,   :validate => true

  attribute :message,   :validate => true


  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Nouveau contact",
      :to => "antoine.staumont@gmail.com",
      :from => %("#{nom}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end

end

app/controllers/cabinets_controller.rb
class CabinetsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index,:show, :new]

  # GET /cabinets or /cabinets.json
  def index
    @cabinets = Cabinet.all


    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @cabinets.geocoded.map do |cabinet|
      {
        lat: cabinet.latitude,
        lng: cabinet.longitude,
        info_window: render_to_string(partial: "info_window", locals: { cabinet: cabinet })

      }
    end
  end



  # GET /cabinets/1 or /cabinets/1.json
  def show

    @cabinets = Cabinet.all


    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @cabinets.geocoded.map do |cabinet|
      {
        lat: cabinet.latitude,
        lng: cabinet.longitude,
        info_window: render_to_string(partial: "info_window", locals: { cabinet: cabinet })

      }
    end

  end

  # GET /cabinets/new
  def new
    @cabinet = Cabinet.new
  end

  # GET /cabinets/1/edit
  def edit
  end

  # POST /cabinets or /cabinets.json
  def create
    @cabinet = Cabinet.new(cabinet_params)


      if @cabinet.save
        flash[:notice] = 'Votre profil a correctement été créé. Il sera validé par un admin, merci.'
        redirect_to cabinet_path(@cabinet)
      else
        flash[:notice] = 'Votre profil a correctement été créé. Il sera validé par un admin, merci.'
        redirect_to new_cabinet_path

    end
  end

  # PATCH/PUT /cabinets/1 or /cabinets/1.json
  def update
    respond_to do |format|
      if @cabinet.update(cabinet_params)
        format.html { redirect_to @cabinet, notice: "Les modifications ont été enregistrées dans la base de données" }
        redirect_to cabinet_path(@cabinet)
      else
        format.html { render :edit, status: :unprocessable_entity }
        cabinet_path(@cabinet)
      end
    end
  end

  # DELETE /cabinets/1 or /cabinets/1.json
  def destroy
    @cabinet.destroy
    respond_to do |format|
      format.html { redirect_to cabinets_url, notice: "Le cabinet a été effacé de la base de données" }
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cabinet

      @cabinet = Cabinet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cabinet_params
      params.require(:cabinet).permit(:name, :address,:phone, :description, photos: [])
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash[:notice] = 'Merci pour votre message. Nous vous recontacterons très vite!'
      redirect_to root_path
    else
      flash[:alert] = 'Un problème est survenu. Veuillez réessayer svp.'
      redirect_to root_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!, only: [:home, :pro, :public, :paris, :mentionslegales]

  def home
  end

  def pro
  end

  def public
  end

  def paris
  end

  def mentionslegales
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cabinets_helper.rb
module CabinetsHelper
end

app/views/cabinets/_form.html.erb
<%= simple_form_for(@cabinet) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<form>
  <div class="mb-3">
    <%= f.input :name ,class:'form-control', label:false, placeholder:'Nom du cabinet'%>

  </div>

  <div class="mb-3">

    <%= f.input :address, id:"exampleInputPassword1" ,class:'form-control', label:false, placeholder:'Adresse du cabinet'%>

  </div>

  <div class="mb-3">

    <%= f.input :phone , id:"exampleInputPassword1",class:'form-control', label:false, placeholder:'Numéro de téléphone du cabinet'%>

  </div>

  <div class="mb-3">

    <%= f.input :description, id:"exampleInputPassword1", class:'form-control' , :as => :text, input_html: {style: 'max-height:1500px;'}, required: true, class: "form-control form-control-last-child", label: false, placeholder:"Description du cabinet" %>

  </div>

  <%= f.input :photos, as: :file, input_html: { multiple: true } %>

    <%= f.button :submit , class:'btn btn-secondary'%>
</form>
<% end %>

app/views/cabinets/_info_window.html.erb
<h2><%= cabinet.name %></h2>
<p><%= cabinet.address %></p>

app/views/cabinets/edit.html.erb
<h1>Editing Cabinet</h1>

<%= render 'form', cabinet: @cabinet %>

<%= link_to 'Show', @cabinet %> |
<%= link_to 'Back', cabinets_path %>

app/views/cabinets/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Cabinets</h1>
<table>
  <tbody>
    <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    <% @cabinets.each do |cabinet| %>
      <tr>
        <td><%= cabinet.name %></td>
        <td><%= cabinet.address %></td>
        <td><%= link_to 'Show', cabinet %></td>
        <td><%= link_to 'Edit', edit_cabinet_path(cabinet) %></td>
        <td><%= link_to 'Destroy', cabinet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Cabinet', new_cabinet_path %>

app/views/cabinets/new.html.erb
<%= render 'shared/navbaradmin'%>

<div class="container" >
  <br>
  <br>
  <br>
  <br>
  <br>
  <h1>AJOUTER UN CABINET</h1>

  <%= render 'form', cabinet: @cabinet %>

</div>


<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"></script>
<script src="../assets/scripts.js"></script>

app/views/cabinets/show.html.erb
<link rel="icon" type="../assets/x-icon" href="../assets/logo.svg" />
<script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
<link href="../assets/styles.css" rel="stylesheet" />
<body id="page-top">
  <%= render'shared/navbarpublicother'%>
  <header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
      <div  id="map"
            style="width: 100%; height: 600px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      <br>
      <h1 class="masthead-heading text-uppercase mb-0">Nos Cabinets</h1>
      <div class="divider-custom divider-light">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
        <div class="divider-custom-line"></div>
      </div>
      <p class="masthead-subheading font-weight-light mb-0">Groupement de cabinets dentaires d'urgences</p>
    </div>
  </header>
  <%= render 'shared/cabinets'%>
  <div class="scroll-to-top d-lg-none position-fixed">
    <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top"><i class="fa fa-chevron-up"></i></a>
  </div>
  <%= render'shared/footer'%>
  <%= render 'shared/portfoliopublic'%>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"></script>
  <script src="../assets/scripts.js"></script>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>GIE SOSDentistes</title>

    <link rel="icon" type="assets/x-icon" href="../assets/logo.svg" />
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="../assets/styles.css" rel="stylesheet" />
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.4.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.4.1/mapbox-gl.css' rel='stylesheet' />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application' %>

    <%= javascript_pack_tag 'application'%>

  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<header class="masthead bg-primary text-white text-center" style="height: 1000px;">
  <div class="container d-flex align-items-center flex-column">
    <img class="masthead-avatar mb-5" class=img-responsive src="assets/logo.svg" alt="..." />
    <div class="text-center mt-4">
      <a class="btn btn-xl btn-outline-light" target='_blank' href="pages/pro">Vous êtes chirurgien-dentiste</a>
    </div>
    <div class="text-center mt-4">
      <a class="btn btn-xl btn-outline-light" target='_blank' href="pages/public">Vous êtes un patient</a>
    </div>
  </div>
</header>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"></script>

app/views/pages/mentionslegales.html.erb
<%if current_user%>
  <%= render 'shared/navbaradmin'%>
<%else%>
  <%= render'shared/navbarpublicother'%>
<%end%>
<%= render 'shared/footer'%>

app/views/pages/nepaseffacer.html.erb
<% if cab.photos.attached?%>
                  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                    <% n = 1%>
                    <% cab.photos.each do |photo| %>
                      <% if n == 1%>
                        <div class="carousel-item active">
                          <%= cl_image_tag photo.key, size:"200x200", crop:"fill", class:"  d-block w-100", alt:"" %>
                          <% n = n+1%>
                        </div>
                      <%else%>
                        <div class="carousel-item ">
                          <%= cl_image_tag photo.key, size:"200x200", crop:"fill", class:" d-block w-100", alt:"" %>
                          <% n = n+1%>
                        </div>
                      <%end%>
                    <%end%>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                  </div>
                <%else%>
                  <img  src="https://res.cloudinary.com/dz83jh064/image/upload/v1631711846/P0D2394399G_j6qsx8.webp"  alt="" size="200*200" crop="fill">
                <%end%>

app/views/shared/_cabinets.html.erb
<section class="page-section" id="contact">
  <div class="container">
    <section class="page-section bg-primary text-white mb-0" id="about">
      <div class="container">
        <div class="row row-cols-1 row-cols-md-3 g-4">
          <% @cabinets = Cabinet.all%>
          <% @cabinets.each do |cab| %>
            <div class="col">
              <div class="card "  >
                <% if cab.photos.attached?%>
                  <% n =1 %>
                  <% cab.photos.each do |photo| %>
                    <% if n ==1%>
                      <%= cl_image_tag photo.key, height: 300, width: 200, crop: :fill ,class:"card-img-top", alt:"" %>
                      <% n = n+1%>
                    <%end%>
                  <% end %>
                <%else%>
                <img  src="https://res.cloudinary.com/dz83jh064/image/upload/v1631711846/P0D2394399G_j6qsx8.webp" class="card-img-top" alt="" style="height:300px; width:295px;" crop="fill">
                <%end%>
                <div class="card-body" >
                  <h5 class="card-title" style="color: black;"><%= cab.name.capitalize %></h5>
                  <p class="card-text" style="color: black; height:100px;"><%= cab.address %></p>
                  <a href="<%=pages_paris_path(cab)%>" class="btn btn-primary">Voir</a>
                  <% if current_user%>
                    <a href="<%= edit_cabinet_path(cab)%>" class="btn btn-primary">Modifier</a>
                    <a href="../pages/paris" class="btn btn-primary" method=":delete, data: { confirm: 'Are you sure?' }">Effacer</a>
                  <% end%>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </section>
  </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer text-center">
  <div class="container">
    <img  src="../assets/logo2.svg" style="width: 200px" alt="..." />
    <div class="row">
      <div class="col-lg-4 mb-5 mb-lg-0">
        <h4 class="text-uppercase mb-4">Notre adresse</h4>
        <p class="lead mb-0">277 Avenue Jean  Garaialde<br/>62152 HARDELOT</p>
      </div>
      <div class="col-lg-4 mb-5 mb-lg-0">
        <h4 class="text-uppercase mb-4">Nos liens sociaux</h4>
        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-linkedin-in"></i></a>
        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-dribbble"></i></a>
      </div>
      <div class="col-lg-4">
        <h4 class="text-uppercase mb-4">Nous contacter</h4>
        <p class="lead mb-0">Tel : 0660954702<br><a href="mailto:infos@sosdentistes.fr">infos@sosdentistes.fr</a></p>
      </div>
    </div>
  </div>
</footer>
<div class="copyright py-4 text-center text-white">
  <div class="container">
    <small>Copyright &copy; SOSDentistes<script>document.write(new Date().getFullYear());</script><a href="<%=pages_mentionslegales_path%>">mentions légales</a></small>
  </div>
</div>

app/views/shared/_mapbox.html.erb
<H1>essai</H1>

<div class="fixed-map">
  <div  id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">SOSDENTISTES</a>
    <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">Notre volonté</a></li>
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">A propos de nous</a></li>
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">Nos cabinets</a></li>

        <% if current_user.nil?%>
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="">Connexion</a></li>
        <%else%>
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="">Déconnexion</a></li>
        <%end%>

      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbaradmin.html.erb
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="<%=root_path%>">SOSDENTISTES</a>
    <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<%=new_cabinet_path%>" onclick="setTimeout(location.reload.bind(location), 1)">Ajouter un cabinet</a></li>
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<%=pages_public_path%>" onclick="setTimeout(location.reload.bind(location), 1)">Accueil public</a></li>
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<%=pages_pro_path%>" onclick="setTimeout(location.reload.bind(location), 1)">Accueil pro</a></li>
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<%=destroy_user_session_path%>">Déconnexion</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbarhome.html.erb
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="<%=root_path%>">SOSDENTISTES</a>
    <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">Notre volonté</a></li>
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">A propos de nous</a></li>
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">Nos cabinets</a></li>

        <% if current_user.nil?%>
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="">Connexion</a></li>
        <%else%>
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="">Déconnexion</a></li>
        <%end%>

      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbarpro.html.erb
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="<%=root_path%>">SOSDENTISTES</a>
    <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">Notre volonté</a></li>
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">A propos de nous</a></li>
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">Nous contacter</a></li>

        <% if current_user.nil?%>
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="" >Connexion</a></li>
        <%else%>
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="">Déconnexion</a></li>
        <%end%>

      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbarpublicother.html.erb
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="<%=root_path%>">SOSDENTISTES</a>
    <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<%=pages_public_path%>" onclick="setTimeout(location.reload.bind(location), 1)">Accueil Public</a></li>

        <% if current_user.nil?%>
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="">Connexion</a></li>
        <%else%>
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="">Déconnexion</a></li>
        <%end%>

      </ul>
    </div>
  </div>
</nav>